.Dd September 16, 2017
.Dt libtableau 3
.Os libtableau
.Sh NAME
.Nm libtableau.h
.Nd Library to support the Tableau(TM) forensic bridge (write blocker)
.Sh LIBRARY
.Lb libtableau
.Sh SYNOPSIS
.In libtableau.h
.Pp
Support functions
.Ft const char *
.Fn libtableau_get_version "void"
.Pp
Notify functions
.Ft void
.Fn libtableau_notify_set_verbose "int verbose"
.Ft int
.Fn libtableau_notify_set_stream "FILE *stream, libtableau_error_t **error"
.Ft int
.Fn libtableau_notify_stream_open "const char *filename, libtableau_error_t **error"
.Ft int
.Fn libtableau_notify_stream_close "libtableau_error_t **error"
.Pp
Error functions
.Ft void
.Fn libtableau_error_free "libtableau_error_t **error"
.Ft int
.Fn libtableau_error_fprint "libtableau_error_t *error, FILE *stream"
.Ft int
.Fn libtableau_error_sprint "libtableau_error_t *error, char *string, size_t size"
.Ft int
.Fn libtableau_error_backtrace_fprint "libtableau_error_t *error, FILE *stream"
.Ft int
.Fn libtableau_error_backtrace_sprint "libtableau_error_t *error, char *string, size_t size"
.Pp
Handle functions
.Ft int
.Fn libtableau_handle_initialize "libtableau_handle_t **handle, libtableau_error_t **error"
.Ft int
.Fn libtableau_handle_free "libtableau_handle_t **handle, libtableau_error_t **error"
.Ft int
.Fn libtableau_open "libtableau_handle_t *handle, const char *filename, libtableau_error_t **error"
.Ft int
.Fn libtableau_close "libtableau_handle_t *handle, libtableau_error_t **error"
.Ft int
.Fn libtableau_query "libtableau_handle_t *handle, libtableau_error_t **error"
.Ft int
.Fn libtableau_detected_dco "libtableau_handle_t *handle, libtableau_error_t **error"
.Ft int
.Fn libtableau_remove_dco "libtableau_handle_t *handle, libtableau_error_t **error"
.Ft int
.Fn libtableau_get_drive_amount_of_sectors "libtableau_handle_t *handle, uint32_t *amount_of_sectors, libtableau_error_t **error"
.Ft int
.Fn libtableau_get_hpa_amount_of_sectors "libtableau_handle_t *handle, uint32_t *amount_of_sectors, libtableau_error_t **error"
.Ft int
.Fn libtableau_get_dco_amount_of_sectors "libtableau_handle_t *handle, uint32_t *amount_of_sectors, libtableau_error_t **error"
.Ft int
.Fn libtableau_get_amount_of_tableau_values "libtableau_handle_t *handle, uint32_t *amount_of_values, libtableau_error_t **error"
.Ft int
.Fn libtableau_get_tableau_value_identifier "libtableau_handle_t *handle, uint32_t index, char *value, size_t length, libtableau_error_t **error"
.Ft int
.Fn libtableau_get_tableau_value "libtableau_handle_t *handle, char *identifier, char *value, size_t length, libtableau_error_t **error"
.Pp
Available when compiled with wide character string support:
.Ft int
.Fn libtableau_open_wide "libtableau_handle_t *handle, const wchar_t *filename, libtableau_error_t **error"
.Sh DESCRIPTION
The
.Fn libtableau_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return type.
For the actual return values see "libtableau.h".
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
libtableau allows to be compiled with wide character support (wchar_t).

To compile libtableau with wide character support use:
.Ar ./configure --enable-wide-character-type=yes
 or define:
.Ar _UNICODE
 or
.Ar UNICODE
 during compilation.

.Ar LIBTABLEAU_WIDE_CHARACTER_TYPE
 in libtableau/features.h can be used to determine if libtableau was compiled with wide character support.
.Sh BUGS
Please report bugs of any kind on the project issue tracker: https://github.com/libyal/libtableau/issues
.Sh AUTHOR
These man pages are generated from "libtableau.h".
.Sh COPYRIGHT
Copyright (C) 2008-2017, Joachim Metz <joachim.metz@gmail.com>.

This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libtableau.h include file
